#! /bin/sh
### BEGIN INIT INFO
# Provides:          cstbox-zwave
# Required-Start:    $remote_fs $syslog cstbox-dbus cstbox-evtmgr
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: CSTBox ZWAve devices support service
# Description:       This package adds to an existing CSTBox framework the support
#                    for ZWave interfaced devices. 
#                    It includes the models of currently support products.
### END INIT INFO

# Author: Patrick POLLET <patrick.pollet@cstb.fr>

DESC="CSTBox ZWave HAL"
INIT_SEQ=94
NAME=cstbox-zwave
DAEMON=/opt/cstbox/bin/zwave.py
DAEMON_ARGS=
INIT_VERBOSE=yes

. /opt/cstbox/lib/init/init-functions
